### ISSUE TITLE
Can we move this out of alphagov please?

### ISSUE THREAD

**Issue by boffbowsh** [alphagov/govuk-guix#32]
We need to start only using alphagov for official GDS repositories. Can I transfer this to your personal github account please @cbaines ? Additionally, we'll need to stop building this in GOV.UK CI for similar reasons.

**Comment by cbaines** [comment]
> We need to start only using alphagov for official GDS repositories. Can I transfer this to your personal github account please @cbaines ?

What is the motivation behind looking to remove this repository?

I ask because, removing this repository would break the current setup for updating the package definitions (the commits by the Package Updater).

This would make running and developing GOV.UK applications more difficult for me, as using this software is currently the best way I've found to develop software for GOV.UK, something which I've been using and improving since the start of 2017.

**Comment by boffbowsh** [comment]
Every repository on alphagov must be owned by a team within GDS, and it's something we're working towards. I'm starting with GOV.UK-related repositories. You'll notice I've raised a number of issues on repositories across alphagov today asking to either clarify their usage, remove them or move them to gds-attic. I've removed the `govuk` topic tag for this repository as we're now using those tags as a trigger to mirror repositories to Gitlab.

The only supported way to work on GOV.UK is via the development VM, so we can't as a programme commit to maintaining this as well. For the same reason, we'll soon need to move that Package Updater job out of Jenkins.

It's ok if you really want to work this way, but it isn't ideal for a number of reasons:

1. It adds potential friction when pairing with other members of GOV.UK. They may need to first understand your build process as well as understand what you're working on
2. It creates confusion - anyone stumbling upon these repositories (both inside and outside GOV.UK) may assume this is needed to build and run GOV.UK, and waste time trying to get it running
3. You're not contributing usability fixes to the supported development process, so the rest of the GOV.UK developer community is missing out on your expertise
4. Others in GOV.UK have [found](https://github.com/alphagov/govuk-guix/commits?author=elenatanasoiu) [references](https://github.com/alphagov/govuk-guix/commits?author=fofr) in this repository to applications they are working to retire, and have had to spend time understanding what they need to remove, working under the assumption that this is an essential repository

**Comment by cbaines** [comment]
> Every repository on alphagov must be owned by a team within GDS, and it's something we're working towards. I'm starting with GOV.UK-related repositories. You'll notice I've raised a number of issues on repositories across alphagov today asking to either clarify their usage, remove them or move them to gds-attic. I've removed the govuk topic tag for this repository as we're now using those tags as a trigger to mirror repositories to Gitlab.

I appreciate the effort to curate the collection Git repositories. But, to comment more generally mandating that each repository be owned by a team, assuming this is equivalent to the concept of "ownership" by product managers in GOV.UK. I highly value this space for the collaboration it enables, obviously for supporting work on projects owned by product managers, but also on everything that is either too small or too general to be owned by a product manager at any particular time. I don't know of another way of hosting Git repositories where you can give specific access to those who work at GOV.UK or GDS, now and in the future.

While I created the govuk-guix repository last year for sharing within the now disbanded Publishing Platform team, I've continued to work on govuk-guix as it's helpful to me working on GOV.UK, and because I hope that it can benefit others, which is why I have intentionally continued to work on govuk-guix publicly and where others have access, because I want to enable and at least put effort towards making it possible for others to benefit from this as I have. It's for this specific reason (and personal convenience as I mentioned previously) that I'm in favour of keeping this repository in the alphagov organisation.

> The only supported way to work on GOV.UK is via the development VM, so we can't as a programme commit to maintaining this as well. For the same reason, we'll soon need to move that Package Updater job out of Jenkins.
> 
> It's ok if you really want to work this way, but it isn't ideal for a number of reasons:

Grouping the following points differently:

>   1. It adds potential friction when pairing with other members of GOV.UK. They may need to first understand your build process as well as understand what you're working on

I totally accept this, and effective pairing practices is something I'm working on improving. While I'm aware that working using different tooling for the development environment does have a cost in the way you describe, I've been attempting to be careful with pairing mostly due to using Emacs as a editor, and try to make sure people are interested in using the tooling I do, before doing so.

>   3. You're not contributing usability fixes to the supported development process, so the rest of the GOV.UK developer community is missing out on your expertise

For this I can only apologise. The usability problems I was having when I switched to using govuk-guix were related to the mandatory use of virtualisation, and the management of the software within the virtual machine (both that which I was working on, and that required to do so). I perceive these as intractable, but I accept that there may have been improvements I could have made elsewhere even if I didn't attempt to address these bigger issues.

>   2. It creates confusion - anyone stumbling upon these repositories (both inside and outside GOV.UK) may assume this is needed to build and run GOV.UK, and waste time trying to get it running
>   4. Others in GOV.UK have found references in this repository to applications they are working to retire, and have had to spend time understanding what they need to remove, working under the assumption that this is an essential repository

I totally understand and accept that this repository can and has caused confusion and extra work, and for this I can only apologise. While there is some documentation and descriptions, I haven't explicitly tried yet to do anything about these points you've raised.

Back to the topic though, I think I've put forward my points on keeping this now, and thank you for taking the time to reply. Unless you'd like to continue discussing this, if you'd still like to remove this from the alphagov organisation, I'd suggest deleting it, as I try not to use my personal GitHub account for hosting Git repositories and it doesn't have the same sharing and access properties that the alphagov organisation has.

**Comment by boffbowsh** [comment]
Ok. I'll delete these repositories at the end of the day on Monday. You're right that this is a useful collaboration space for people to experiment with things within GDS. However, experiments need tidying up if they don't get any uptake or don't meet the needs. There's no one else in GOV.UK that uses Guix to develop, so I think this meets that criteria.

**Comment by cbaines** [comment]
I'm closing this issue, as it's old and I'm not sure there's any use in keeping it open.
